version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@5.1
jobs:
  setup_ts_server:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: teamspeak-server
      - run: >-
          aws cloudformation deploy
          --region eu-west-1
          --stack-name teamspeak-server
          --capabilities CAPABILITY_NAMED_IAM
          --template-file ./infra.yml
          --no-fail-on-empty-changeset
workflows:
  aws-cli:
    jobs:
      - setup_ts_server:
          context: aws